-- TRUNCATE TABLE Quote;

INSERT INTO Quote (QuoteBG, QuoteEN) VALUES
    (N'"Да бъдеш или да не бъдеш, това е въпросът."', N'"To be or not to be, that is the question"'),
    (N'"Който се смее над белега, не знае що е рана."', N'"He jests at scars that never felt a wound."'),
    (N'"Дори да си студена като лед и чиста като сняг, пак не ще избегнеш клеветата."', N'"Be thou as chaste as ice, as pure as snow, thou shalt not escape calumny."'),
    (N'"Целият свят е сцена и всички ние сме актьори на нея - влизаме, излизаме и за своето време всеки от нас играе различни роли..."', N'"All the world''s a stage, and all the men and women merely players: they have their exits and their entrances; and one man in his time plays many parts."'),
    (N'"Вината… не е в нашите звезди… а в нас самите."', N'"The fault… is not in our stars… but in ourselves."'),
    (N'"Не звездите държат нашата съдба, а ние самите."', N'"It is not in the stars to hold our destiny but in ourselves."'),
    (N'"Живеят само влюбените, останалите просто съществуват."', N'"Only the people in love live, others just exist."'),
    (N'"Еретик не е този, който изгаря на кладата, а този, който я подпалва."', N'"It is an heretic that makes the fire, Not she which burns in it."'),
    (N'"Едно красиво сърце е по-добро от хиляди красиви лица."', N'"One beautiful heart is better than thousand beautiful faces."'),
    (N'"Глупакът си въобразява, че е умен, но мъдрият знае , че е глупак."', N'"A fool thinks himself to be wise, but a wise man knows himself to be a fool."'),
    (N'"Моята корона се нарича съдържание и малцина крале й се радват."', N'"My crown is called content, a crown that seldom kings enjoy."'),
    (N'"По-добре три часа по-рано, отколкото минута по-късно."', N'"Better three hours too soon than a minute late."'),
    (N'"Обичай всички, доверявай се на малцина, не прави зло на никого."', N'"Love all, trust a few, do wrong to none."'),
    (N'"Подозрението винаги преследва виновния ум."', N'"Suspicion always haunts the guilty mind."'),
    (N'"Винаги грешният човек ти дава правилния урок в живота."', N'"Always the wrong person gives you the right lesson in life."'),
    (N'"Когато те видях, се влюбих, а ти се усмихна, защото знаеше."', N'"When I saw you, I fell in love, and you smiled, because you knew."'),
    (N'"Животът е твърде кратък, за да те обичам само веднъж. Обещавам да те потърся в следващия."', N'"Life is too short to love you in one, I promise to look for you in the next life."'),
    (N'"Обичай ме или ме мрази, и двете са в моя полза: ако ме обичаш, ще съм винаги в сърцето ти. Ако ме мразиш, ще съм винаги в ума ти."', N'"Love me or hate me, both are in my favor. For if you love me I will always be in your heart; if you hate me I will always be in your mind."'),
    (N'"Никога не си играй с чувствата на другите, защото, може да спечелиш играта, но със сигурност ще изгубиш човека доживот."', N'"Never play with the feelings of others, because you may win the game but the risk is that you will surely lose the person for lifetime."'),
    (N'"Очите са прозорец към душата."', N'"The Eyes are the window to your soul."'),
    (N'"Не прикривай отровата със сладки думи."', N'"Hide not thy poison with such sugared words."'),
    (N'"Адът е празен и всички дяволи са тук."', N'"Hell is empty and all the devils are here."'),
    (N'"Няма друго наследство, по-богато от честността."', N'"No legacy is so rich as honesty."'),
    (N'"Слушай мнозина, говори с малко."', N'"Listen to many, speak to a few."'),
    (N'"Очите виждат всичко, но умът ни показва само това, което иска да види."', N'"The eye sees all, but the mind shows us what we want to see."'),
    (N'"Няма нищо по-ограничаващо от затвора на собствените ни възприятия."', N'"There is nothing so confining as the prisons of our own perceptions."'),
    (N'"Имай повече, отколкото показваш, говори по-малко, отколкото знаеш."', N'"Have more than you show, speak less than you know."'),
    (N'"Всяко безумие има своята логика."', N'"Every why has a wherefore."'),
    (N'"Когато се раждаме, проплакваме, за това, че идваме на тази велика сцена на глупци."', N'"When we are born we cry that we are come to this great stage of fools."'),
    (N'"Умът на виновния е пълен със скорпиони."', N'"The mind of guilt is full of scorpions."'),
    (N'"Лицето ти е отворена книга, от която могат да се прочетат странни неща."', N'"Your face is a book, where men may read strange matters."'),
    (N'"За да направиш велики неща правилно, извършваш малки грешно."', N'"To do a great right do a little wrong."'),
    (N'"О, докато си жив, казвай само истината и засрами Дявола!"', N'"O, while you live, tell truth, and shame the Devil!"'),
    (N'"Сълзите поливат нашето израстване."', N'"Tears water our growth."'),
    (N'"Любовта е най-великата мечта и най-лошият кошмар."', N'"Love is the greatest of dreams, yet the worst of nightmares."'),
    (N'"Мечтай в светлинни години, предизвиквай в мили, върви стъпка по стъпка."', N'"Dream in light years, challenge miles, walk step by step."'),
    (N'"Грях е да бъдеш присмехулник."', N'"It is a sin to be a mocker."'),
    (N'"Бог ти даде едно лице и ти си направи друго."', N'"God has given you one face, and you make yourself another."'),
    (N'"Ще те запиша в книгата си на спомени."', N'"I''ll note you in my book of memory."'),
    (N'"Ако тълпата може да обича без да знае защо, тя също може да мрази без особено основание."', N'"If the masses can love without knowing why, they also hate without much foundation."'),
    (N'"И той вървеше през живота с отворена уста и затворен ум."', N'"And he goes through life, his mouth open, and his mind closed."'),
    (N'"Повече от твоя разговор ще възпали мозъка ми."', N'"More of your conversation would infect my brain."'),
    (N'"Мъжете на малкото думи са най-добрите."', N'"Men of few words are the best men."'),
    (N'"Няма как да изгубиш играта, ако не играеш."', N'"You can''t lose a game if you don''t play the game."'),
    (N'"Бъди търпелив, защото светът е голям и широк."', N'"Be patient, for the world is broad and wide."'),
    (N'"Нека вървим ръка за ръка, а не един пред друг."', N'"Let''s go hand in hand, not one before another."'),
    (N'"Няма нищо по-близко до молитвата от музиката."', N'"There is nothing in the world so much like prayer as music is."'),
    (N'"Тежка е царската корона."', N'"Uneasy lies the head that wears a crown."'),
    (N'"Времето тече много бавно за онези, които чакат, много бързо за онези, които са изплашени, много дълго за онези, които тъгуват, много кратко за онези, които празнуват, но за онези, които обичат, времето е вечност."', N'"Time is very slow for those who wait, very fast for those who are scared, very long for those who lament, very short for those who celebrate, but for those who love, time is eternal."'),
    (N'"Ако обичаш и боли, обичай повече. Ако обичаш повече, и боли повече, обичай още повече. Ако обичаш още повече и боли още повече, обичай дори още малко повече, докато спре да боли повече."', N'"If you love and get hurt, love more. If you love more and hurt more, love even more. If you love even more and get hurt even more, love some more until it hurts no more…"'),
    (N'"Земята има своя музика за тези, които ще слушат, нейните ярки вариации изобилстват завинаги; С всички чудеса, които Бог ни е завещал, няма нищо, което да вълнува така, както магията на звука."', N'"The earth has its music for those who will listen, Its bright variations forever abound; With all the wonders that God has bequeathed us, There is nothing that thrills like the magic of sound."');
